apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-gunicorn
  name: flask-gunicorn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-gunicorn
  strategy: {}
  template:
    metadata:
      labels:
        app: flask-gunicorn
    spec:
      containers:
        - image: flask-gunicorn:v1
          name: flask-gunicorn
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: GUNICORN_CMD_ARGS
              value: "--workers=3 --access-logfile -"
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 20m
              memory: 24Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
status: {}
